apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertmanager

data:
  alertmanager.yml: |
    global:
      resolve_timeout: 16m

    templates: 
      - ./*.tmpl

    inhibit_rules:
    # Mute warnings for which also a critical alert exists.
    # Per context and region.
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['context']
    - source_match:
        severity: 'critical|warning'
      target_match:
        severity: 'info'
      equal: ['context']

    route:
      group_by: ['region', 'alertname']
      group_wait: 1m
      group_interval: 7m
      repeat_interval: 12h
      receiver: dev-null

      routes:

      # staging, lab alerts > /dev/null
      - receiver: dev-null
        continue: false
        match_re:
          region: .*staging|lab

      # routing per tier to <tier>-{info, warning, critical} channel
      {{- range $tier := .Values.tiers }}
      - receiver: {{ $tier }}-info
        continue: true
        match_re:
          tier: {{ $tier }}
        routes:
        - receiver: '{{ $tier }}-warning'
          continue: true
          match:
            severity: warning
        - receiver: '{{ $tier }}-critical'
          continue: true
          match:
            severity: critical
      {{- end }}

      # routing per service to openstack-<service> channel
      {{- range $service := .Values.openstack_services }}
      - receiver: openstack-{{ $service }}
        continue: true
        match_re:
          service: {{ $service }}
          tier: openstack
      {{- end }}

      # staging, qa-de-1, lab, scaleout, internet cluster alerts > /dev/null
      - receiver: dev-null
        continue: false
        match_re:
          region: .*staging|.*qa-de-1|lab|s-.*|i-.*

      # routing to pagerduty channels
      {{- range $pd := .Values.pagerduty }}
      - receiver: pagerduty-{{ $pd.name }}
        continue: false
        {{- if $pd.alerts }}
        match_re:
          alertname: {{ join "|" $pd.alerts -}}
        {{- end }}
      {{- end }}

    receivers:
    - name: dev-null
      slack_configs:
      - api_url: {{ default "MISSING" $.Values.slack.webhook_url | quote }}
        username: "Kubernetes Control Plane"
        channel: "#dev-null"
        title: {{"'{{template \"slack.sapcc.title\" . }}'"}}
        title_link: {{"'{{template \"slack.sapcc.titlelink\" . }}'"}}
        text: {{"'{{template \"slack.sapcc.text\" . }}'"}}
        pretext: {{"'{{template \"slack.sapcc.pretext\" . }}'"}}
        icon_emoji: {{"'{{template \"slack.sapcc.iconemoji\" . }}'"}}
        send_resolved: true

    # <tier>-{info, warning, critical} receiver
    {{- range $tier := .Values.tiers }}
    {{- range $severtity := tuple "info" "warning" "critical" }}
    - name: {{ $tier }}-{{ $severtity }}
      slack_configs:
      - api_url: {{ default "MISSING" $.Values.slack.webhook_url | quote }}
        username: "{{ $tier | title }} Control Plane"
        channel: "#{{ $tier }}-{{ $severtity }}"
        title: {{"'{{template \"slack.sapcc.title\" . }}'"}}
        title_link: {{"'{{template \"slack.sapcc.titlelink\" . }}'"}}
        text: {{"'{{template \"slack.sapcc.text\" . }}'"}}
        pretext: {{"'{{template \"slack.sapcc.pretext\" . }}'"}}
        icon_emoji: {{"'{{template \"slack.sapcc.iconemoji\" . }}'"}}
        send_resolved: true
    {{- end }}
    {{- end }}

    # openstack-<service> receivers
    {{- range .Values.openstack_services }}
    - name: openstack-{{ . }}
      slack_configs:
      - api_url: {{ default "MISSING" $.Values.slack.webhook_url | quote }}
        username: "OpenStack Control Plane"
        channel: "#openstack-{{ . }}"
        title: {{"'{{template \"slack.sapcc.title\" . }}'"}}
        title_link: {{"'{{template \"slack.sapcc.titlelink\" . }}'"}}
        text: {{"'{{template \"slack.sapcc.text\" . }}'"}}
        pretext: {{"'{{template \"slack.sapcc.pretext\" . }}'"}}
        icon_emoji: {{"'{{template \"slack.sapcc.iconemoji\" . }}'"}}
        send_resolved: true
    {{- end }}

    {{- range $pd := .Values.pagerduty_services }}
    - name: pagerduty-{{ $pd.name }}
      pagerduty_configs:
      - service_key: {{ default "" $pd.service_key }}
        description: {{"'{{ template \"pagerduty.sapcc.description\" . }}'"}}
        component: {{"'{{template \"pagerduty.sapcc.tier\" . }}'"}}
        group: {{"'{{template \"pagerduty.sapcc.service\" . }}'"}}
        details:
          Details: {{"'{{template \"pagerduty.sapcc.details\" . }}'"}}
          Region: {{"'{{template \"pagerduty.sapcc.region\" . }}'"}}
          Tier: {{"'{{template \"pagerduty.sapcc.tier\" . }}'"}}
          Service: {{"'{{template \"pagerduty.sapcc.service\" . }}'"}}
          Context: {{"'{{template \"pagerduty.sapcc.context\" . }}'"}}
          Prometheus: {{"'{{template \"pagerduty.sapcc.prometheus\" . }}'"}}
          Dashboard: {{"'{{template \"pagerduty.sapcc.dashboard\" . }}'"}}
          Sentry: {{"'{{template \"pagerduty.sapcc.sentry\" . }}'"}}
          Playbook: {{"'{{template \"pagerduty.sapcc.playbook\" . }}'"}}
          firing: {{"'{{ template \"pagerduty.sapcc.firing\" . }}'"}}
    {{- end }}

  {{- $files := .Files }}
  {{ range tuple "slack.tmpl" "pagerduty.tmpl" }}
  {{ . }}: |
{{ $files.Get . | indent 4 }}
  {{- end }}
