apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertmanager

data:
  alertmanager.yml: |
    global:
      resolve_timeout: 16m

    templates: 
      - ./*.tmpl

    inhibit_rules:
    # Mute warnings for which also a critical alert exists.
    # Per context and region.
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['context']
    - source_match:
        severity: 'critical|warning'
      target_match:
        severity: 'info'
      equal: ['context']

    route:
      group_by: ['region', 'alertname']
      group_wait: 1m
      group_interval: 7m
      repeat_interval: 12h
      receiver: dev-null

      routes:
      - receiver: dev-null
        continue: false
        match_re:
          region: .*staging|lab

      - receiver: slack_by_tier_and_severity
        match_re:
          tier: openstack|kubernetes|kubernikus|baremetal
          severity: info|warning|critical

      - receiver: slack_by_tier_and_service
        match_re:
          tier: openstack
          severity: info|warning|critical
          service: arc|backup|barbican|cinder|designate|elektra|elk|ironic|keystone|limes|lyra|maia|manila|neutron|nova|swift

      - receiver: pagerduty_baremetal
        match_re:
          severity: critical
          region: ap-ae-1|ap-au-1|ap-cn-1|ap-jp-1|ap-jp-2|ap-sa-1|eu-de-1|eu-de-2|eu-nl-1|eu-ru-1|la-br-1|na-ca-1|na-us-1|na-us-3
          tier: baremetal

      - receiver: pagerduty_hypervisor
        match_re:
          severity: critical
          region: [^.*qa-de-1]
          service: vcenter

      - receiver: pagerduty
        match_re:
          severity: critical
          region: ap-ae-1|ap-au-1|ap-cn-1|ap-jp-1|ap-jp-2|ap-sa-1|eu-de-1|eu-de-2|eu-nl-1|eu-ru-1|la-br-1|na-ca-1|na-us-1|na-us-3
          tier: openstack|kubernetes

      - receiver: pagerduty
        match_re:
          severity: warning
          region: [^.*qa-de-1]
          alertname: KubernetesBond.*

    receivers:
    - name: dev-null
      slack_configs:
      - api_url: {{ default "MISSING" $.Values.slack.webhook_url | quote }}
        username: "Kubernetes Control Plane"
        channel: "#dev-null"
        title: {{"'{{template \"slack.sapcc.title\" . }}'"}}
        title_link: {{"'{{template \"slack.sapcc.titlelink\" . }}'"}}
        text: {{"'{{template \"slack.sapcc.text\" . }}'"}}
        pretext: {{"'{{template \"slack.sapcc.pretext\" . }}'"}}
        icon_emoji: {{"'{{template \"slack.sapcc.iconemoji\" . }}'"}}
        send_resolved: true

    - name: slack_by_tier_and_severity
      slack_configs:
        - channel: "{{.CommonLabels.tier}}-{{.CommonLabels.severity}}"
          api_url: {{ default "MISSING" .Values.slack.webhook_url | quote }}
          username: "Kubernetes Control Plane"
          channel: "#dev-null"
          title: {{"'{{template \"slack.sapcc.title\" . }}'"}}
          title_link: {{"'{{template \"slack.sapcc.titlelink\" . }}'"}}
          text: {{"'{{template \"slack.sapcc.text\" . }}'"}}
          pretext: {{"'{{template \"slack.sapcc.pretext\" . }}'"}}
          icon_emoji: {{"'{{template \"slack.sapcc.iconemoji\" . }}'"}}
          send_resolved: true

    - name: slack_by_tier_and_service
      slack_configs:
        - channel: "{{.CommonLabels.tier}}-{{.CommonLabels.service}}"
          api_url: {{ default "MISSING" .Values.slack.webhook_url | quote }}
          username: "Kubernetes Control Plane"
          channel: "#dev-null"
          title: {{"'{{template \"slack.sapcc.title\" . }}'"}}
          title_link: {{"'{{template \"slack.sapcc.titlelink\" . }}'"}}
          text: {{"'{{template \"slack.sapcc.text\" . }}'"}}
          pretext: {{"'{{template \"slack.sapcc.pretext\" . }}'"}}
          icon_emoji: {{"'{{template \"slack.sapcc.iconemoji\" . }}'"}}
          send_resolved: true

    - name: pagerduty
      pagerduty_configs:
        - service_key: {{ default "MISSING" .Values.pagerduty.default.service_key | quote }}
          description: {{"'{{ template \"pagerduty.sapcc.description\" . }}'"}}
          component: {{"'{{template \"pagerduty.sapcc.tier\" . }}'"}}
          group: {{"'{{template \"pagerduty.sapcc.service\" . }}'"}}
          details:
            Details: {{"'{{template \"pagerduty.sapcc.details\" . }}'"}}
            Region: {{"'{{template \"pagerduty.sapcc.region\" . }}'"}}
            Tier: {{"'{{template \"pagerduty.sapcc.tier\" . }}'"}}
            Service: {{"'{{template \"pagerduty.sapcc.service\" . }}'"}}
            Context: {{"'{{template \"pagerduty.sapcc.context\" . }}'"}}
            Prometheus: {{"'{{template \"pagerduty.sapcc.prometheus\" . }}'"}}
            Dashboard: {{"'{{template \"pagerduty.sapcc.dashboard\" . }}'"}}
            Sentry: {{"'{{template \"pagerduty.sapcc.sentry\" . }}'"}}
            Playbook: {{"'{{template \"pagerduty.sapcc.playbook\" . }}'"}}
            firing: {{"'{{ template \"pagerduty.sapcc.firing\" . }}'"}}

    - name: pagerduty_baremetal
      pagerduty_configs:
        - service_key: {{ default "MISSING" .Values.pagerduty.baremetal.service_key | quote }}
          description: {{"'{{ template \"pagerduty.sapcc.description\" . }}'"}}
          component: {{"'{{template \"pagerduty.sapcc.tier\" . }}'"}}
          group: {{"'{{template \"pagerduty.sapcc.service\" . }}'"}}
          details:
            Details: {{"'{{template \"pagerduty.sapcc.details\" . }}'"}}
            Region: {{"'{{template \"pagerduty.sapcc.region\" . }}'"}}
            Tier: {{"'{{template \"pagerduty.sapcc.tier\" . }}'"}}
            Service: {{"'{{template \"pagerduty.sapcc.service\" . }}'"}}
            Context: {{"'{{template \"pagerduty.sapcc.context\" . }}'"}}
            Prometheus: {{"'{{template \"pagerduty.sapcc.prometheus\" . }}'"}}
            Dashboard: {{"'{{template \"pagerduty.sapcc.dashboard\" . }}'"}}
            Sentry: {{"'{{template \"pagerduty.sapcc.sentry\" . }}'"}}
            Playbook: {{"'{{template \"pagerduty.sapcc.playbook\" . }}'"}}
            firing: {{"'{{ template \"pagerduty.sapcc.firing\" . }}'"}}

    - name: pagerduty_hypervisor
      pagerduty_configs:
        - service_key: {{ default "MISSING" .Values.pagerduty.hypervisor.service_key | quote }}
          description: {{"'{{ template \"pagerduty.sapcc.description\" . }}'"}}
          component: {{"'{{template \"pagerduty.sapcc.tier\" . }}'"}}
          group: {{"'{{template \"pagerduty.sapcc.service\" . }}'"}}
          details:
            Details: {{"'{{template \"pagerduty.sapcc.details\" . }}'"}}
            Region: {{"'{{template \"pagerduty.sapcc.region\" . }}'"}}
            Tier: {{"'{{template \"pagerduty.sapcc.tier\" . }}'"}}
            Service: {{"'{{template \"pagerduty.sapcc.service\" . }}'"}}
            Context: {{"'{{template \"pagerduty.sapcc.context\" . }}'"}}
            Prometheus: {{"'{{template \"pagerduty.sapcc.prometheus\" . }}'"}}
            Dashboard: {{"'{{template \"pagerduty.sapcc.dashboard\" . }}'"}}
            Sentry: {{"'{{template \"pagerduty.sapcc.sentry\" . }}'"}}
            Playbook: {{"'{{template \"pagerduty.sapcc.playbook\" . }}'"}}
            firing: {{"'{{ template \"pagerduty.sapcc.firing\" . }}'"}}

  {{- $files := .Files }}
  {{ range tuple "slack.tmpl" "pagerduty.tmpl" }}
  {{ . }}: |
{{ $files.Get . | indent 4 }}
  {{- end }}
