image:
  repository: prom/alertmanager
  tag: v0.15.2

global:
  region: DEFINED-IN-SECRETS
  domain: DEFINED-IN-SECRETS

cluster:
  listen_address: DEFINED-IN-SECRETS
  peer_timeout: 60s
  probe_timeout: 60s
  tcp_timeout: 60s
  # peers:
  #   - DEFINED-IN-SECRETS

persistence:
  name: data-prometheus-alertmanager
  access_mode: ReadWriteMany
  size: 1Gi

configmap_reload:
  image:
    repository: jimmidyson/configmap-reload
    tag: v0.2.2

slack:
  webhook_url: DEFINED-IN-SECRETS

# creates <tier>-{info, warning, critical} routing and receivers
tiers:
  - kubernetes
  - kubernikus
  - openstack
  - baremetal

# creates openstack-<service> routing and receivers
openstack_services:
  - arc
  - backup
  - barbican
  - cinder
  - designate
  - elektra
  - elk
  - ironic
  - keystone
  - limes
  - lyra
  - maia
  - manila
  - neutron
  - nova
  - swift

pagerduty:
  # name of the pagerduty receiver
  - name: pagerduty
    # pagerduty service key
    service_key: DEFINED-IN-SECRETS
    # limit alerts to this receiver to the following names. regex possible.
    alerts:
      - KubernetesKubeletManyDown
      - KubernetesNodeNetworkBond.*
