global:
  region: DEFINED-IN-SECRETS
  domain: DEFINED-IN-SECRETS

image:
  repository: prom/alertmanager
  tag: v0.15.2

configmap_reload:
  image:
    repository: jimmidyson/configmap-reload
    tag: v0.2.2

cluster:
  listen_address: DEFINED-IN-SECRETS
  peer_timeout: 60s
  probe_timeout: 60s
  tcp_timeout: 60s
  # peers:
  #   - DEFINED-IN-SECRETS

persistence:
  name: data-prometheus-alertmanager
  access_mode: ReadWriteMany
  size: 1Gi

slack:
  webhook_url: DEFINED-IN-SECRETS

pagerduty:
  default:
    service_key: DEFINED-IN-SECRETS

  baremetal:
    service_key: DEFINED-IN-SECRETS

  hypervisor:
    service_key: DEFINED-IN-SECRETS
